// <auto-generated />
namespace Task.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddUrlImage_and_ShortBio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUrlImage_and_ShortBio));
        
        string IMigrationMetadata.Id
        {
            get { return "201707181414477_AddUrlImage_and_ShortBio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
